#!/bin/bash
# Node.js安装脚本

echo "=== Node.js安装指南 ==="
echo ""
echo "由于系统没有Homebrew，请选择以下方式之一安装Node.js："
echo ""
echo "方式1: 从官网下载安装包（推荐）"
echo "  1. 访问 https://nodejs.org/"
echo "  2. 下载 macOS 安装包（.pkg文件）"
echo "  3. 双击安装"
echo ""
echo "方式2: 使用nvm安装（推荐开发者使用）"
echo "  运行以下命令："
echo "  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash"
echo "  source ~/.zshrc"
echo "  nvm install --lts"
echo "  nvm use --lts"
echo ""
echo "安装完成后，运行以下命令验证："
echo "  node --version"
echo "  npm --version"
echo ""
echo "然后运行："
echo "  cd frontend"
echo "  npm install"
echo "  npm run dev"
