"""Round-2 LLM augmentation cases (Artifact 4 §12 — improvement with evidence).

These 3 cases were generated by AutoTestDesign's /api/improve (second-round LLM
augmentation), then HUMAN-REVIEWED: 8 suggestions in, 3 accepted (2 with the LLM's
oracle corrected), 5 rejected (out of Module A scope / SUT does not model / invented
DTCs). Source + review notes: docs/test_evidence/improve_round2_accepted.json.

Run AFTER the baseline 96 to measure whether the additions cover new behavior:
    coverage run --branch -m pytest tests/test_suite_from_design.py tests/test_improve_round2.py
"""
import json
from pathlib import Path

import pytest

import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "vcu_simulator"))
from simulator import VCUSimulator  # noqa: E402

_CASES = json.loads((ROOT / "docs/test_evidence/improve_round2_accepted.json").read_text(encoding="utf-8"))
_RESULTS: list = []


def _idata(case):
    return {i["name"]: i.get("value") for i in case.get("in_data", [])}


def _match(actual, op, expected):
    if op == "eq":
        return actual == expected or str(actual) == str(expected)
    if op == "ne":
        return not (actual == expected or str(actual) == str(expected))
    if op == "contains":
        return isinstance(actual, list) and expected in actual
    try:
        a, e = float(actual), float(expected)
    except (TypeError, ValueError):
        return False
    return {"gte": a >= e, "lte": a <= e, "gt": a > e, "lt": a < e}.get(op, False)


def _run(sim, case):
    """Mini-adapter for the 3 concurrent/extreme scenarios the round-2 cases probe."""
    req = case["requirement_id"]
    d = _idata(case)
    if not d:  # coverage-gap case: no wake signal at all → fallthrough (L273) → maintain sleep
        return sim.simulate()
    if req == "REQ-011":  # concurrent sleep + wake → sleep precedence
        return sim.simulate(
            VCUO_bDIAG_VCUIdle_flg=int(d.get("h1", 1)),
            VCUO_bDIAG_AuthComplete_flg=int(d.get("h2", 1)),
            can_stopped=(int(d.get("h3", 1)) == 1),
            supply_voltage=float(d.get("voltage")),
            duration_ms=15,
        )
    if req == "REQ-004":  # concurrent CC + CC2 → CC precedence
        return sim.simulate(cc_voltage=float(d["cc_voltage"]), cc2_voltage=float(d["cc2_voltage"]))
    if req == "REQ-006":  # extreme long duration
        return sim.simulate(hood_voltage=float(d["hood_voltage"]), duration_ms=int(d["duration_ms"]))
    raise AssertionError(f"no round-2 adapter for {req}")


@pytest.fixture(scope="session", autouse=True)
def _dump():
    yield
    out = ROOT / "docs/test_evidence/pytest_output/improve_round2_execution.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(_RESULTS, ensure_ascii=False, indent=2, default=str), encoding="utf-8")


@pytest.mark.parametrize("case", _CASES, ids=[c["id"] for c in _CASES])
def test_round2(case):
    sim = VCUSimulator()
    sim.reset()
    resp = _run(sim, case)
    failures = []
    for e in case["expected_results"]:
        if not _match(resp.get(e["name"]), e["operator"], e["value"]):
            failures.append(f"{e['name']} {e['operator']} {e['value']!r} (actual={resp.get(e['name'])!r})")
    _RESULTS.append({
        "id": case["id"], "requirement_id": case["requirement_id"], "technique": case["technique"],
        "title": case["title"], "input": _idata(case),
        "expected": [(e["name"], e["operator"], e["value"]) for e in case["expected_results"]],
        "actual_output": resp, "passed": not failures, "mismatches": failures,
    })
    assert not failures, "; ".join(failures)
